# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9135abb89f06357d8275d22e03edbbff"
name = "product-discount-app"
handle = "product-discount-app-117"
application_url = "https://yr-women-refurbished-association.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "apps-learning-with-js.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://yr-women-refurbished-association.trycloudflare.com/auth/callback",
  "https://yr-women-refurbished-association.trycloudflare.com/auth/shopify/callback",
  "https://yr-women-refurbished-association.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
