# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc0ae1a381ca126a22574cfd0e4a8b30"
name = "order-discount-app"
handle = "order-discount-app-10"
application_url = "https://critical-end-develop-franchise.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "apps-learning-with-js.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://critical-end-develop-franchise.trycloudflare.com/auth/callback",
  "https://critical-end-develop-franchise.trycloudflare.com/auth/shopify/callback",
  "https://critical-end-develop-franchise.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
