# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a7fa5e3ae6b99453619ec2ac774384bb"
name = "payment-customization"
handle = "payment-customization-68"
application_url = "https://patches-setup-comprehensive-organ.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "apps-learning-with-js.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://patches-setup-comprehensive-organ.trycloudflare.com/auth/callback",
  "https://patches-setup-comprehensive-organ.trycloudflare.com/auth/shopify/callback",
  "https://patches-setup-comprehensive-organ.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
