# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9950a6b09924c99cf41f34369bc0579"
name = "checkout-validation"
handle = "checkout-validation-87"
application_url = "https://approval-mart-videos-newcastle.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "apps-learning-with-js.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://approval-mart-videos-newcastle.trycloudflare.com/auth/callback",
  "https://approval-mart-videos-newcastle.trycloudflare.com/auth/shopify/callback",
  "https://approval-mart-videos-newcastle.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
